

spring:
  profile:
    active: test
  tast:
    scheduling:
      pool:
        size: 2

server:
  port: 8082
  tomcat:
    threads:
      max: 300


logging:
  file:
    name: logs/log_v1_1.log

---
#test 환경
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    hikari:
      maximum-pool-size: 375

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    show-sql: false
    generate-ddl: true

property:
  upbitCron:
    tick:
      doubleCheck:
        cronCommand: 00 */5 * * * *
        period: 5
      restartSessions:
        cronCommand : 00 */8 * * * *

    orderbook:
      restartSessions:
        cronCommand: 00 */23 * * * *

    candle:
      period:
        cronCommand: 00 */3 * * * *

  bithumbCron:
    candle:
      period:
        cronCommand: 00 */5 * * * *


logging:
  level:
    org:
      springframework:
        cache: DEBUG


    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG


---
#prod 환경
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-01.cohovelkyjmq.ap-northeast-2.rds.amazonaws.com:5432/v1
    username: postgres
    password: postgres1
    hikari:
      maximum-pool-size: 30
      leakDetectionThreshold: 200000

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create

property:
  upbitCron:
    tick:
      doubleCheck:
        cronCommand: 00 */15 * * * *
        period: 15
      restartSessions:
        cronCommand : 00 00 00 * * *

    orderbook:
      restartSessions:
        cronCommand: 00 10 00 */5 * *

    candle:
      period:
        cronCommand: 00 */3 * * * *

  bithumbCron:
    tick:
      restartSessions:
        cronCommand : 00 17 00 * * *
    orderbook:
      restartSessions:
        cronCommand: 01 12 00 * * *

logging:
  level:
    org:
      springframework:
        cache: TRACE

    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE


---
#dev 환경
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.9:5432/v1
    username: postgres1
    password: postgres1
    hikari:
      maximum-pool-size: 375
      leakDetectionThreshold: 20000

    h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create

property:
  upbitCron:
    tick:
      doubleCheck:
        cronCommand: 00 */5 * * * *
        period: 10
      restartSessions:
        cronCommand : 00 */8 * * * *

    orderbook:
      restartSessions:
        cronCommand: 00 */3 * * * *

    candle:
      period:
        cronCommand: 00 */4 * * * *

  bithumbCron:
    candle:
      period:
        cronCommand: 00 00 * * * *

    tick:
      restartSessions:
        cronCommand: 00 17 00 * * *

    orderbook:
      restartSessions:
        cronCommand: 01 12 00 * * *

logging:
  level:
    org:
      springframework:
        cache: TRACE

    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
